name: disaster_response_pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas=2.0.3
  - numpy=1.24.4
  - pip=24.0
  - scikit-learn=1.3.2
  - pytest=8.2.0
  - jupyter=1.0.0
  - jupyterlab=4.2.0
  - nltk=3.8.1
  - flask=3.0.3
  - sqlalchemy=2.0.30
  - plotly=5.22.0
  - requests=2.31.0
  - matplotlib=3.7.3
  - seaborn=0.13.2
  - xgboost=2.0.3
  - wordcloud=1.9.3